// Theme configuration for multiple color variants
export const themes = {
  neonBlue: {
    primary: '#00F0FF',
    secondary: '#6366F1',
    accent: '#D946EF',
    background: '#0f172a',
    card: '#1e293b',
  },
  cyberpunk: {
    primary: '#D946EF',
    secondary: '#EC4899',
    accent: '#00F0FF',
    background: '#0d0221',
    card: '#200338',
  },
  minimalDark: {
    primary: '#3B82F6',
    secondary: '#8B5CF6',
    accent: '#EC4899',
    background: '#0F172A',
    card: '#1E293B',
  },
}

// Skills data
export const skillsData = {
  languages: [
    { name: 'Python', proficiency: 95, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
    { name: 'JavaScript', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
    { name: 'Java', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
    { name: 'C++', proficiency: 80, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg' },
    { name: 'C', proficiency: 82, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg' },
    { name: 'R', proficiency: 84, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg' },
    { name: 'HTML', proficiency: 93, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg' },
    { name: 'CSS', proficiency: 92, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg' },
    { name: 'SQL', proficiency: 88, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
  ],
  frameworks: [
    { name: 'React', proficiency: 92, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
    { name: 'Node.js', proficiency: 88, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
    { name: 'Express.js', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
    { name: 'Django', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg' },
    { name: 'Spring Boot', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg' },
    { name: 'TensorFlow', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg' },
    { name: 'Flask', proficiency: 82, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg' },
    { name: 'MongoDB', proficiency: 87, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
  ],
  cloud: [
    { name: 'Microsoft Azure', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg' },
    { name: 'Oracle OCI', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg' },
    { name: 'AWS', proficiency: 80, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg' },
    { name: 'Google Cloud', proficiency: 78, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg' },
  ],
  tools: [
    { name: 'Git', proficiency: 95, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
    { name: 'VS Code', proficiency: 98, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg' },
    { name: 'Docker', proficiency: 82, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
    { name: 'Jupyter', proficiency: 88, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg' },
    { name: 'Google Colab', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecolab/googlecolab-original.svg' },
    { name: 'Tableau', proficiency: 86, icon: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Tableau_Logo.png' },
    { name: 'Power BI', proficiency: 85, icon: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/New_Power_BI_Logo.svg' },
  ],
}

// Projects data
export const projectsData = [
  {
    id: 1,
    title: 'Detection and Classification of Cardiac Arrhythmia Using Machine Learning',
    category: ['AI/ML', 'Full-Stack'],
    shortDescription: 'AI-powered diagnostic tool for real-time ECG analysis and clinical reporting',
    fullDescription: 'State-of-the-art ECG Arrhythmia Detection system using Weighted KNN for classifying 13+ arrhythmia types. Features multi-source input support (CSV, images, manual data), interactive Plotly dashboards for wave analysis, automated PDF clinical reports, doctor portal, and integrated Telegram/Email notifications for high-risk events.',
    image: 'https://admin.sarojhospital.com/storage/images/Irregular-Heartbeat---Types,-Prognosis-and-Life-Expectancy.png',
    tags: ['Python', 'Flask', 'Machine Learning', 'Weighted KNN', 'OpenCV', 'ReportLab'],
    metrics: { accuracy: '98.89%', classes: '13+ arrhythmias', features: 'Real-time analysis' },
    github: 'https://github.com/Jaideep193/Cardiac_Arrhythmia_Detection_And_Classification.git',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 2,
    title: 'Forest Fire Detection using CNN',
    category: 'Computer Vision',
    shortDescription: 'Early forest fire detection system using Convolutional Neural Networks',
    fullDescription: 'Deep learning project that detects forest fires in images using CNN architecture. Real-time binary classification (Fire/No Fire) with 95.2% accuracy. Features automated image preprocessing, data augmentation, and fast inference for environmental monitoring and disaster management integration.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=675&fit=crop',
    tags: ['Python', 'TensorFlow', 'CNN', 'Deep Learning', 'OpenCV', 'Kaggle'],
    metrics: { accuracy: '95.2%', precision: '94.8%', recall: '96.1%' },
    github: 'https://github.com/Jaideep193/Forest_Fire_Detection',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 3,
    title: 'Facial Attendance System',
    category: 'Computer Vision',
    shortDescription: 'Real-time face recognition system for automated attendance tracking',
    fullDescription: 'Python-based attendance management using LBPH (Local Binary Patterns Histograms) face recognition. Captures webcam face samples, trains custom model, and marks attendance in real-time with duplicate prevention. Complete data persistence with trained model weights and label mappings.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8XzARxbgYT9mM5Ijf1EpOCrTaQ0kVNKKYNA&s',
    tags: ['Python', 'OpenCV', 'LBPH', 'Machine Learning', 'Face Recognition'],
    metrics: { accuracy: '98%+', realtime: 'Yes', users: 'Unlimited' },
    github: 'https://github.com/Jaideep193/Facial_Attendance_System',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 4,
    title: 'Delhi AQI Time Series Analysis',
    category: 'Data Science',
    shortDescription: 'Comprehensive air quality forecasting using SARIMA modeling',
    fullDescription: 'End-to-end analysis of Delhi AQI with 16-month dataset (Jan 2024-Apr 2025). SARIMA-based 30-day forecasting achieving MAE 120.13 and R² 0.76. Features seasonal decomposition, pollutant correlation analysis, and public health impact assessment. Includes interactive visualizations and policy recommendations.',
    image: 'https://c.ndtvimg.com/2024-11/ajaqgeq8_delhi-air-pollution_625x300_28_November_24.jpeg?im=FeatureCrop,algorithm=dnn,width=545,height=307',
    tags: ['Python', 'SARIMA', 'Pandas', 'Matplotlib', 'Time Series', 'Statsmodels'],
    metrics: { MAE: '120.13', RMSE: '140.50', datapoints: '365+' },
    github: 'https://github.com/Jaideep193/Delhi_AQI',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 5,
    title: 'Hand Gesture Recognition',
    category: 'Computer Vision',
    shortDescription: 'Real-time hand gesture detection and classification',
    fullDescription: 'Computer vision project for recognizing hand gestures using Python and OpenCV. Implements gesture-based control system with real-time processing capabilities.',
    image: 'https://miro.medium.com/1*O-RLj8Sa2f86RFoBonmtig.jpeg',
    tags: ['Python', 'OpenCV', 'Computer Vision', 'Gesture Recognition'],
    metrics: { realtime: 'Yes', gestures: '10+', fps: '30+' },
    github: 'https://github.com/Jaideep193/-Hand_Gestures_',
    liveDemo: '#',
    featured: false,
  },
  {
    id: 6,
    title: 'ADGENESIS - AI-Powered Design Platform',
    category: ['AI/ML', 'Full-Stack'],
    shortDescription: 'Canva-inspired platform that generates ads, posters, and social posts using AI',
    fullDescription: 'ADGENESIS is a full-stack AI design platform that converts text prompts into professional designs in seconds. It includes a Fabric.js-powered canvas editor, 50+ templates, brand kit management, multi-format export, and a custom fine-tuned GPT-2 model for design blueprint generation. Built with React, FastAPI, and a PyTorch ML pipeline.',
    image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&h=675&fit=crop',
    tags: ['React', 'FastAPI', 'Fabric.js', 'PyTorch', 'PostgreSQL', 'Tailwind CSS'],
    metrics: { templates: '50+', exports: 'PNG/JPG/SVG', model: 'GPT-2' },
    github: 'https://github.com/18vikastg/adgenesis',
    liveDemo: 'https://adgenesis.vercel.app/',
    featured: true,
  },

]

// Education data
export const educationData = [
  {
    id: 1,
    title: 'Bachelor of Engineering - ISE',
    institution: 'JSS Academy Of Technical Education, Bangalore',
    year: '2022 - 2026',
    details: 'Specialized in AI/ML, Cloud Computing, Full-Stack Development',
    cgpa: '9.03+',
    icon: '🎓',
  },
  {
    id: 2,
    title: 'PUC (XII)',
    institution: 'Rock Valley Residential PU College, Kolar',
    year: '2020 - 2022',
    details: 'Physics, Chemistry, Mathematics, Biology',
    percentage: '96.33%',
    icon: '📚',
  },
  {
    id: 2,
    title: 'SSLC (X)',
    institution: 'Sri Venu Vidya Samasthe, Srinivaspura',
    year: '2019 - 2020',
    details: 'Mathematics, Science, Social Studies, English, Kannada, Hindi',
    percentage: '96%',
    icon: '📚',
  },
]

// Certifications data
export const certificationsData = [
  {
    id: 1,
    title: 'Microsoft Azure Fundamentals (AZ-900)',
    institution: 'Microsoft',
    year: '2025',
    details: 'Cloud concepts, Azure architecture and services, Azure management and governance',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-us/JaideepMC-3064/29E89F813C34FCC4?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  },
  {
    id: 2,
    title: 'Microsoft Azure Data Fundamentals (DP-900)',
    institution: 'Microsoft',
    year: '2025',
    details: 'Core data concepts, Relational data on Azure, Non-relational data on Azure, Analytics workload on Azure',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-us/JaideepMC-3064/A215EF73E5076D0E?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  },
  {
    id: 3,
    title: 'Microsoft Power Platform Fundamentals (PL-900)',
    institution: 'Microsoft',
    year: '2025',
    details: 'Business value of Microsoft Power Platform, Power Platform environment, Capabilities of Power Apps, Power Automate and Power Pages',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-us/JaideepMC-3064/2B8526E6FA0DBCDF?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  },
  {
    id: 4,
    title: 'Oracle Cloud Infrastructure 2025 Certified AI Foundations Associate',
    institution: 'Oracle',
    year: '2024',
    details: 'OCI AI services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=5F30B8171CE9526CCEC5F1F075ECD496D83ED58CE5B53860ACF153E7DC2B2621',
    icon: '🌐',
  },
  {
    id: 5,
    title: 'Oracle Cloud Infrastructure 2025 Certified Foundations Associate',
    institution: 'Oracle',
    year: '2025',
    details: 'OCI services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=D75E5981D26CB89D3BF8529358C9997863620903ABBD91AF58C01CB84BBEE07E',
    icon: '🌐',
  },
  {
    id: 6,
    title: 'NVIDIA-Certified Associate: Generative AI LLMs',
    institution: 'NVIDIA',
    year: '2025',
    details: 'Artificial Intelligence (AI), Large Language Models (LLM), Machine Learning, Deep Learning',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/sco/2/21/Nvidia_logo.svg',
    logoColor: 'text-green-500',
    link: 'https://www.credly.com/badges/2081a2fc-91d3-4edb-9035-3bbf67da7eef/linked_in_profile',
    icon: '⚙️🤖🧠',
  },
  {
    id: 7,
    title: 'Neo4j Certified Professional',
    institution: 'GraphAcademy',
    year: '2025',
    details: 'Neo4j Fundamentals, Cypher Fundamentals, Using Neo4j with Python, Graph Data Modeling Fundamentals, Importing Data Fundamentals, Intermediate Cypher Queries',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/neo4j/neo4j-original.svg',
    logoColor: 'text-cyan-400',
    link: 'https://graphacademy.neo4j.com/c/8ce96653-983f-4c97-8b56-dd8bd6fe1264/',
    icon: '🕸️',
  },
  {
    id: 8,
    title: 'Oracle Cloud Infrastructure 2025 Certified Generative AI Professional',
    institution: 'Oracle',
    year: '2025',
    details: 'OCI AI services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=E6E7536E5B4BC66E997ED7250699B2D7F78842F92A8E5FDF1FD3639CDDE01782',
    icon: '🌐',
  },
  {
    id: 9,
    title: 'Oracle Cloud Infrastructure 2025 Certified Data Science Professional',
    institution: 'Oracle',
    year: '2025',
    details: 'OCI Data and ML services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=88552EA17855BFDA1C2E1C0B4F66D9EAECDEF161578F5F97793CF231D280360C',
    icon: '🌐',
  },
  {
    id: 10,
    title: 'Microsoft Azure AI Fundamentals (AZ-900)',
    institution: 'Microsoft',
    year: '2026',
    details: 'Cloud concepts, Azure AI Workloads, ML, Gen-AI, Computer Vision, NLP, Responsibilities of AI',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-in/JaideepMC-3064/4B39B5884E329D4F?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  }
]

// Internships data
export const internshipsData = [
  {
    id: 1,
    title: 'Data Analytics Intern',
    company: 'VOIS',
    duration: 'October 2024 - November 2024',
    location: 'Bangalore, India (Remote)',
    details: 'Analyzed business data to identify trends, patterns, and actionable insights',
    achievements: '📈 Improved data query performance by 35% | 📊 Created 8+ interactive dashboards',
    responsibilities: [
      'Analyzed business data to identify trends, patterns, and actionable insights using statistical methods',
      'Created data visualizations and interactive dashboards using Excel, SQL, and Python for stakeholder presentations',
      'Performed rigorous statistical analysis and A/B testing on datasets to validate hypotheses',
      'Optimized complex SQL queries and database operations achieving 35% faster data retrieval',
      'Translated complex data findings into clear, actionable business recommendations for management',
    ],
    skills: ['Python', 'SQL', 'Excel', 'Data Visualization', 'Statistical Analysis', 'Tableau'],
    icon: '📊',
  },
  {
    id: 2,
    title: 'AI/ML Intern',
    company: 'TechSaksham | Microsoft & SAP (CSR Initiative)',
    duration: 'November 2024 - December 2024',
    location: 'Bengaluru, India (Remote)',
    details: 'Developed a real-time Facial Attendance System using Python, OpenCV, and Machine Learning',
    achievements: '✅ 98% face recognition accuracy ',
    responsibilities: [
      'Developed real-time Facial Attendance System with automated webcam-based identification and attendance recording',
      'Implemented LBPH (Local Binary Patterns Histogram) face recognition achieving 98% accuracy under varied lighting conditions',
      'Designed end-to-end data pipeline for dataset creation, model training, and persistent storage of weights and mappings',
      'Built automated attendance logging system recording Name, Date, Time with duplicate prevention mechanisms',
      'Created modular architecture suitable for classroom attendance, employee tracking, and access control systems',
    ],
    skills: ['Python', 'OpenCV', 'Machine Learning', 'LBPH', 'Computer Vision', 'Image Processing'],
    icon: '🤖',
  },
  {
    id: 3,
    title: 'AI & Data Analytics Intern',
    company: 'Edunet Foundation | AICTE | Shell (Skills4Future)',
    duration: 'April 2025',
    location: 'Bengaluru, India (Virtual)',
    details: 'Developed an early forest fire detection system using Convolutional Neural Networks (CNNs)',
    achievements: '🔥 95% accuracy | 🚀 Real-time inference | 🌍 Environmental impact solution',
    responsibilities: [
      'Developed CNN-based forest fire detection system achieving 95% classification accuracy on test data',
      'Implemented comprehensive image processing pipeline with resizing, normalization, and advanced data augmentation techniques',
      'Designed and trained deep CNN architecture using TensorFlow with optimized feature extraction layers',
      'Achieved exceptional model performance with high precision, recall, and F1-score for reliable fire detection',
      'Built production-ready solution for environmental monitoring with potential integration into disaster management systems',
    ],
    skills: ['Python', 'TensorFlow', 'CNNs', 'Computer Vision', 'Deep Learning', 'Image Processing', 'Keras'],
    icon: '🔥',
  },
]

// Accomplishments data
export const accomplishmentsData = [
  {
    id: 1,
    title: 'Participated in Tesco Retail Media InnoItion Hackathon',
    achievement: 'Built AI-Powered Ad Design Platform',
    details: 'Organized by Tesco, developed ADGENESIS, an AI-powered design platform that generates ads, posters, and social posts using React, FastAPI, and a custom GPT-2 model',
    date: '2025-2026',
    impact: 'Selected as one of the top 15 teams for final round out of 8700 candidates and 2000+ team entries.',
    icon: '👨‍💻 ',
  },
  
  {
    id: 2,
    title: 'Participated in Quantum Quest 24HR Hackathon',
    achievement: 'Built Arrhythmia Detection System with 98.89% accuracy',
    details: 'Organized by C. Byre Gowda Institute of Technology, developed an Arrhythmia detection system to solve a real-world problem',
    date: '2025',
    impact: 'Out of 65+ teams, our project was selected in the top 10 for its creativity and potential impact',
    icon: ' 👩‍💻',
  },
  {
    id: 3,
    title: 'Participated Hack Together: AI Agents Hackathon',
    achievement: 'Built AI Chatbot',
    details: 'Organized by Microsoft, developed an AI chatbot using Azure OpenAI and Power Platform for a real-world use case',
    date: '2025',
    impact: 'Got $200 free Azure credits and mentorship from Microsoft AI experts throughout the hackathon',
    icon: '📄',
  },
  {
    id: 4,
    title: 'Participated in Google Cloud Arcade Program',
    achievement: 'Learned Google Cloud Skills and Built Projects',
    details: 'Completed 10+ Google Cloud Arcade quests covering core GCP services, AI/ML, and cloud architecture. Built hands-on projects and earned badges for each quest',
    date: '2025',
    impact: 'Reached Legend status in Google Cloud Arcade, demonstrating proficiency in GCP and cloud-native development and earned Google swag for completing quests and received 600 Google Cloud credits',
    icon: '🏆',
  },
  {
    id: 5,
    title: 'Participated in Bhartiya Antariksh Hackathon 2025',
    achievement: 'Built Forest Fire Detection System',
    details: 'Organized by ISRO and Hack2Skill, developed a real-time forest fire detection system using CNNs to address environmental challenges',
    date: '2025',
    impact: 'Innovative approach to environmental monitoring',
    icon: '🚀',
  },
  {
    id: 6,
    title: 'Participated in Paranox 2.O Hackathon',
    achievement: 'Academic Excellence',
    details: 'Participated in Paranox 2.0 Hackathon, organized by TechXNinjas, held from 20th August 2025 to 16th November 2025.',
    date: '2025',
    impact: 'Over 1,552 projects and 20,119 students participated nationwide ',
    icon: '🌟',
  },
  {
    id: 7,
    title: 'Participated in Elite Coders Winter of Code (ECWOC) 2025',
    achievement: 'Academic Excellence',
    details: 'Participated in Elite Coders Winter of Code (ECWOC) 2025, organized by Elite Coders',
    date: '2025',
    impact: '5000+ participants, demonstrating dedication to open source and the developer community',
    icon: '🌟',
  },
  {
    id: 8,
    title: 'Gemini Certified University Student from Google for Education',
    achievement: 'Academic Excellence',
    details: 'Certified in Gemini AI by Google for Education, demonstrating proficiency in using Gemini for AI development and applications',
    date: '2025',
    impact: 'Recognized by Google for Education for AI proficiency, showcasing commitment to learning and applying cutting-edge AI technologies',
    icon: '👩‍💻',
  },
  {
    id: 9,
    title: 'NPTEL Online Certification for Python for Data Science (Elite🏅)!',
    achievement: 'Academic Excellence',
    details: 'Completed the NPTEL Online Certification for Python for Data Science, demonstrating proficiency in Python programming and data science concepts',
    date: '2025',
    impact: 'Scored 80/100 and in top 5 percentile, showcasing strong understanding of Python for data science and commitment to continuous learning',
    icon: '👩‍💻',
  },
  {
    id: 10,
    title: 'Attended the Google Cloud virtual Security Summit (Asia Pacific)',
    achievement: 'Academic Excellence',
    details: 'Received recognition! Attending 5+ knowledge-packed sessions has enriched my knowledge of AI-driven cloud security and current industry trends',
    date: '2025',
    impact: 'Attended 5+ sessions on AI-driven cloud security, gaining insights into the latest trends and best practices in cloud security from Google experts',
    icon: '🌟',
  },
  {
    id: 11,
    title: 'Attended AWS Summit India',
    achievement: 'Academic Excellence',
    details: 'AWS Summit India provided a compelling look into the future of digital infrastructure, reaffirming that the conversation has shifted from mere cloud adoption to cloud-driven business acceleration',
    date: '2025',
    impact: 'Received 25 USD AWS credits and attended sessions on cloud-driven business acceleration, gaining insights into how AWS is enabling innovation and transformation across industries',
    icon: '👩‍💻',
  },
  {
    id: 12,
    title: 'Successfully completed the Machine Learning Specialization by DeepLearning.AI and Stanford Online and Stanford University by instructor Andrew Ng on Coursera',
    achievement: 'Academic Excellence',
    details: 'Completed the Machine Learning Specialization, demonstrating proficiency in machine learning concepts and applications',
    date: '2025',
    impact: 'Gained comprehensive understanding of machine learning algorithms and their practical applications, enhancing my skills in AI and data science',
    icon: '👩‍💻',
  },
  {
    id: 13,
    title: 'Officially completed the IBM Machine Learning Professional Certificate',
    achievement: 'Academic Excellence',
    details: 'Completed the IBM Machine Learning Professional Certificate, demonstrating proficiency in machine learning concepts and applications',
    date: '2025',
    impact: 'Gained comprehensive understanding of machine learning algorithms and their practical applications, enhancing my skills in AI and data science',
    icon: '👩‍💻',
  },
  {
    id: 14,
    title: ' Participate in the IBM TechXchange Dev Day: Open Source LLMs 🌐🤖',
    achievement: 'Academic Excellence',
    details: ' Attended the IBM TechXchange Dev Day focused on Open Source Large Language Models (LLMs), gaining insights into the latest advancements and applications of LLMs in AI development',
    date: '2025',
    impact: 'Gained valuable knowledge on open source LLMs and their impact on AI development, showcasing commitment to staying updated with cutting-edge AI technologies',
    icon: '👩‍💻',
  },
]

// Statistics
export const stats = [
  { label: 'Projects Completed', value: '6+' },
  { label: 'Certifications', value: '4' },
  { label: 'Years Experience', value: '3+' },
  { label: 'Happy Clients', value: '100%' },
]
