// Theme configuration for multiple color variants
export const themes = {
  neonBlue: {
    primary: '#00F0FF',
    secondary: '#6366F1',
    accent: '#D946EF',
    background: '#0f172a',
    card: '#1e293b',
  },
  cyberpunk: {
    primary: '#D946EF',
    secondary: '#EC4899',
    accent: '#00F0FF',
    background: '#0d0221',
    card: '#200338',
  },
  minimalDark: {
    primary: '#3B82F6',
    secondary: '#8B5CF6',
    accent: '#EC4899',
    background: '#0F172A',
    card: '#1E293B',
  },
}

// Skills data
export const skillsData = {
  languages: [
    { name: 'Python', proficiency: 95, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
    { name: 'JavaScript', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
    { name: 'Java', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
    { name: 'C++', proficiency: 80, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg' },
    { name: 'C', proficiency: 82, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg' },
    { name: 'R', proficiency: 84, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg' },
    { name: 'HTML', proficiency: 93, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg' },
    { name: 'CSS', proficiency: 92, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg' },
    { name: 'SQL', proficiency: 88, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
  ],
  frameworks: [
    { name: 'React', proficiency: 92, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
    { name: 'Node.js', proficiency: 88, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
    { name: 'Express.js', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
    { name: 'Django', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg' },
    { name: 'Spring Boot', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg' },
    { name: 'TensorFlow', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg' },
    { name: 'Flask', proficiency: 82, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg' },
    { name: 'MongoDB', proficiency: 87, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
  ],
  cloud: [
    { name: 'Microsoft Azure', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg' },
    { name: 'Oracle OCI', proficiency: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg' },
    { name: 'AWS', proficiency: 80, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg' },
    { name: 'Google Cloud', proficiency: 78, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg' },
  ],
  tools: [
    { name: 'Git', proficiency: 95, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
    { name: 'VS Code', proficiency: 98, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg' },
    { name: 'Docker', proficiency: 82, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
    { name: 'Jupyter', proficiency: 88, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg' },
    { name: 'Google Colab', proficiency: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecolab/googlecolab-original.svg' },
    { name: 'Tableau', proficiency: 86, icon: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Tableau_Logo.png' },
    { name: 'Power BI', proficiency: 85, icon: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/New_Power_BI_Logo.svg' },
  ],
}

//Projects
export const projectsData = [
  {
    id: 1,
    title: 'Chandrayaan-2 Lunar Subsurface Ice Detection',
    category: ['AI/ML', 'Data Science'],
    shortDescription: 'Remote-sensing pipeline detecting subsurface water ice in lunar south polar regions using Chandrayaan-2 SAR data',
    fullDescription: 'End-to-end remote-sensing pipeline designed to detect and characterize subsurface water ice in the lunar south polar Faustini Permanently Shadowed Region. Integrates Chandrayaan-2 DFSAR compact-polarimetry data, high-resolution optical imagery, Bayesian statistical inference, and Random Forest ML validation. Uses dual-criterion ice detection combining Circular Polarization Ratio and Degree of Polarization with spatial coherence filtering, physics-based dielectric inversion via the Polder–van Santen model with Monte Carlo uncertainty propagation, AHP-based landing site evaluation, A* rover traverse optimization, and an interactive 8-tab Plotly dashboard with 17 publication-quality figure outputs.',
    image: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=1200&h=675&fit=crop',
    tags: ['Python', 'SAR Processing', 'Bayesian Inference', 'Random Forest', 'scikit-learn', 'Rasterio', 'NumPy', 'SciPy', 'Plotly'],
    metrics: { 'Dashboard': '8-tab Plotly', 'Ice Detection': 'Dual-criterion SAR', 'Data Source': 'Chandrayaan-2 DFSAR' },
    github: 'https://github.com/Jaideep193/Subsurface-Ice-Lunar-South-Polar',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 2,
    title: 'Cardiac Arrhythmia Detection & Classification',
    category: ['AI/ML', 'Full-Stack'],
    shortDescription: 'AI-powered diagnostic system for real-time ECG analysis classifying 16 arrhythmia types with automated clinical reporting',
    fullDescription: 'AI-powered diagnostic system for real-time ECG analysis and clinical reporting using a Weighted KNN classifier that identifies 16 arrhythmia types. Supports multi-source ECG input (CSV, high-resolution images, manual physiological data), interactive Plotly.js dashboards visualizing P, QRS, and T wave patterns, automated clinical PDF report generation via ReportLab, a doctor portal for patient and appointment management, and instant SMTP email alerts for high-risk cardiac events. Backend built with Flask and SQLite3; frontend with HTML5, CSS3, and JavaScript.',
    image: 'https://admin.sarojhospital.com/storage/images/Irregular-Heartbeat---Types,-Prognosis-and-Life-Expectancy.png',
    tags: ['Python', 'Flask', 'Weighted KNN', 'scikit-learn', 'OpenCV', 'ReportLab', 'SQLite3', 'Plotly.js'],
    metrics: { accuracy: '98.89%', classes: '16 arrhythmia types', reports: 'Automated PDF' },
    github: 'https://github.com/Jaideep193/Cardiac_Arrhythmia_Detection_And_Classification',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 3,
    title: 'Forest Fire Probability Mapping & Spread Simulation',
    category: ['AI/ML', 'Data Science'],
    shortDescription: 'AI/ML pipeline for next-day forest fire probability mapping and multi-hour spread simulation using NASA VIIRS satellite data',
    fullDescription: 'End-to-end ML solution predicting forest fire probability and simulating spread across the Kumaon & Garhwal Himalaya region (Uttarakhand, India). Ingests real NASA FIRMS VIIRS satellite fire detections, generates physics-informed synthetic terrain and weather datasets, trains a balanced Random Forest classifier on an 11-channel raster feature stack (elevation, slope, aspect, temperature, humidity, wind, rainfall, LULC), and produces next-day fire probability maps at 30-meter spatial resolution. Models multi-hour fire spread using vectorized 8-neighborhood Cellular Automata incorporating wind, slope, and fuel physics. Full 6-stage pipeline completes in ~10–15 minutes; outputs include GeoTIFF maps, PNG, animated GIF, and a summary dashboard.',
    image: 'https://github.com/Jaideep193/forest-fire-detection/raw/main/outputs/animations/fire_spread_animation.gif',
    tags: ['Python', 'Random Forest', 'scikit-learn', 'NASA VIIRS', 'Cellular Automata', 'Rasterio', 'GeoTIFF', 'NumPy', 'SciPy'],
    metrics: { 'ROC-AUC': '~91%', 'OOB Score': '~0.96', resolution: '30m GeoTIFF', features: '11-channel stack' },
    github: 'https://github.com/Jaideep193/forest-fire-detection',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 4,
    title: 'ADGENESIS - AI-Powered Design Platform',
    category: ['AI/ML', 'Full-Stack'],
    shortDescription: 'Canva-inspired platform that generates ads, posters, and social posts using AI in seconds',
    fullDescription: 'ADGENESIS is a full-stack AI design platform that converts text prompts into professional designs in seconds. Built for the Tesco Retail Media InnoItion Hackathon, it features a Fabric.js-powered canvas editor, 50+ design templates, brand kit management, multi-format export (PNG/JPG/SVG), and a custom fine-tuned GPT-2 model for design blueprint generation. Built with React, FastAPI, and a PyTorch ML pipeline. Selected as one of the top 15 teams out of 8700 candidates and 2000+ team entries.',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=675&fit=crop',
    tags: ['React', 'FastAPI', 'Fabric.js', 'PyTorch', 'PostgreSQL', 'Tailwind CSS', 'GPT-2'],
    metrics: { templates: '50+', exports: 'PNG/JPG/SVG', model: 'Fine-tuned GPT-2' },
    github: 'https://github.com/18vikastg/adgenesis',
    liveDemo: 'https://adgenesis.vercel.app/',
    featured: true,
  },
  {
    id: 5,
    title: 'AI-Based Forest Fire Detection (Supervised ML)',
    category: ['AI/ML', 'Data Science'],
    shortDescription: 'AI-based forest fire detection using satellite imagery and environmental data with supervised ML classification',
    fullDescription: 'Machine learning project for detecting forest fires using satellite imagery and environmental sensor data through supervised classification. Applies feature extraction and preprocessing on multi-source geospatial inputs, trains a supervised ML classifier to distinguish fire vs. non-fire scenes, and evaluates performance for real-world environmental monitoring integration. Built as a Jupyter Notebook-based research pipeline.',
    image: 'https://github.com/Jaideep193/forest-fire-detection/raw/main/outputs/dashboard.png',
    tags: ['Python', 'scikit-learn', 'Satellite Imagery', 'Supervised ML', 'NumPy', 'Pandas', 'Matplotlib', 'Jupyter Notebook'],
    metrics: { type: 'Supervised Classification', input: 'Satellite + Environmental', language: 'Jupyter Notebook' },
    github: 'https://github.com/Jaideep193/Forest_Fire_Detection',
    liveDemo: '#',
    featured: false,
  },
  {
    id: 5,
    title: 'Forest Fire Spread Simulation (NASA VIIRS)',
    category: ['AI/ML', 'Data Science'],
    shortDescription: 'Forest fire spread simulation using real NASA VIIRS satellite fire data and cellular automaton modeling',
    fullDescription: 'A Python-based simulation system that models forest fire spread dynamics using real NASA FIRMS VIIRS satellite fire detection data combined with cellular automaton modeling. Simulates fire propagation based on terrain, wind direction, and vegetation fuel factors to produce realistic multi-step spread predictions. Designed for wildfire risk assessment, emergency response planning, and environmental monitoring applications.',
    image: 'https://raw.githubusercontent.com/Jaideep193/forest-fire/master/outputs/animations/fire_spread_animation.gif',
    tags: ['Python', 'NASA VIIRS', 'Cellular Automaton', 'NumPy', 'Matplotlib', 'Geospatial Analysis'],
    metrics: { 'Data Source': 'NASA FIRMS VIIRS', model: 'Cellular Automaton', language: 'Python' },
    github: 'https://github.com/Jaideep193/forest-fire',
    liveDemo: '#',
    featured: false,
  },
  {
    id: 6,
    title: 'Multimodal AI Chatbot (Gemini 2.0 Flash)',
    category: 'AI/ML',
    shortDescription: 'Multimodal AI chatbot built with Streamlit and Google Gemini 2.0 Flash supporting text, PDF, image, audio, and video',
    fullDescription: "A multimodal AI chatbot application developed with Streamlit and Google's Gemini 2.0 Flash API. Enables users to interact with an AI assistant across five content modalities: text-based conversation, PDF document analysis and querying, image recognition and discussion, audio file processing, and video analysis and information extraction. Features an intuitive chat history UI optimized for local deployment. Built for a hackathon showcasing cutting-edge multimodal LLM capabilities.",
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&h=675&fit=crop',
    tags: ['Python', 'Streamlit', 'Google Gemini 2.0 Flash', 'Generative AI', 'PIL', 'LLM', 'Multimodal AI'],
    metrics: { modalities: '5 (text/PDF/image/audio/video)', model: 'Gemini 2.0 Flash', framework: 'Streamlit' },
    github: 'https://github.com/Jaideep193/Hackathon',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 7,
    title: 'Java Full-Stack E-Commerce Application',
    category: 'Full-Stack',
    shortDescription: 'Console-based Java e-commerce app with MVC architecture, PBKDF2 password hashing, and complete shopping workflow',
    fullDescription: 'A production-oriented console-based e-commerce application built with pure Java, demonstrating full-stack development principles. Implements MVC architecture with secure user authentication (PBKDF2 password hashing), product catalog with search and filtering, shopping cart with real-time calculations, order management, payment processing with transaction history, and an admin dashboard for inventory and report management. Complete data persistence using file-based serialization. The repository also serves as a structured Java learning resource covering OOP, design patterns (Creational, Structural, Behavioral), concurrency, Collections framework, and Stream API across a 12-week curriculum.',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=675&fit=crop',
    tags: ['Java', 'MVC Architecture', 'PBKDF2', 'File Serialization', 'OOP', 'Design Patterns', 'JDK 8+', 'Stream API'],
    metrics: { stars: '3', architecture: 'MVC', security: 'PBKDF2 Hashing' },
    github: 'https://github.com/Jaideep193/Java',
    liveDemo: '#',
    featured: false,
  },
  {
    id: 8,
    title: 'Real-Time Facial Attendance System',
    category: 'Computer Vision',
    shortDescription: 'Real-time facial recognition attendance system using OpenCV with live camera feed and automated CSV/Excel log export',
    fullDescription: "Python-based automated attendance management system using LBPH (Local Binary Patterns Histograms) face recognition. Captures 50 grayscale face samples per user via webcam and stores them in structured folders, trains a custom LBPH recognizer model, and performs real-time face recognition from live camera feed to mark attendance. Features single-daily-log duplicate prevention, persistent storage of trained model weights (face_recognizer.yml) and label mappings (label_map.npy), and attendance records with Name, Date, and Timestamp. Developed during TechSaksham AI/ML internship (Microsoft & SAP CSR Initiative) achieving 98%+ recognition accuracy.",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8XzARxbgYT9mM5Ijf1EpOCrTaQ0kVNKKYNA&s',
    tags: ['Python', 'OpenCV', 'LBPH', 'Face Recognition', 'NumPy', 'Pandas', 'Jupyter Notebook'],
    metrics: { accuracy: '98%+', samples: '50 per user', log: 'CSV with timestamp' },
    github: 'https://github.com/Jaideep193/Facial_Attendance_System',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 9,
    title: 'Delhi AQI Time Series Analysis & Forecasting',
    category: 'Data Science',
    shortDescription: 'End-to-end Delhi air quality analysis with SARIMA-based 30-day forecasting over 16 months of multi-source data',
    fullDescription: "Comprehensive time series analysis and forecasting system for Delhi's air quality patterns, covering 16 months of AQI data (January 2024 – April 2025) for over 30 million NCR residents. Delivers SARIMA-based 30-day ahead forecasting with 95% confidence intervals, seasonal decomposition revealing severe winter deterioration (AQI 380–450), pollutant composition analysis (PM2.5: 60–70%, PM10, NO2, SO2), and a public health impact assessment finding 83.2% of days exceed WHO air quality standards. Includes interactive Plotly visualizations, time series decomposition plots, correlation matrices, and actionable policy recommendations.",
    image: 'https://c.ndtvimg.com/2024-11/ajaqgeq8_delhi-air-pollution_625x300_28_November_24.jpeg?im=FeatureCrop,algorithm=dnn,width=545,height=307',
    tags: ['Python', 'SARIMA', 'Pandas', 'Matplotlib', 'statsmodels', 'Plotly', 'scikit-learn', 'Seaborn'],
    metrics: { MAE: '120.13', RMSE: '140.50', 'R²': '0.76', forecast: '30-day ahead' },
    github: 'https://github.com/Jaideep193/Delhi_AQI',
    liveDemo: '#',
    featured: true,
  },
  {
    id: 10,
    title: 'Hand Gesture Media Control',
    category: 'Computer Vision',
    shortDescription: 'Real-time hand gesture recognition system using MediaPipe and OpenCV that controls media playback via simulated keyboard input',
    fullDescription: 'A computer vision system enabling touchless media control through real-time hand gesture recognition. Uses MediaPipe to track 21 hand landmark points from live webcam feed, classifies multiple gestures (thumbs up/down, raised index finger, lowered finger, open palm, two raised fingers), and translates them into keyboard commands via PyAutoGUI for media playback and volume control. Features live visual feedback overlaying detected hand landmarks, minimal latency response, and requires no hardware beyond a standard webcam.',
    image: 'https://miro.medium.com/1*O-RLj8Sa2f86RFoBonmtig.jpeg',
    tags: ['Python', 'OpenCV', 'MediaPipe', 'PyAutoGUI', 'NumPy', 'Computer Vision'],
    metrics: { landmarks: '21 hand points', gestures: '6+ supported', hardware: 'Webcam only' },
    github: 'https://github.com/Jaideep193/-Hand_Gestures_',
    liveDemo: '#',
    featured: false,
  },
  {
    id: 11,
    title: 'House Price Prediction (Linear Regression)',
    category: ['AI/ML', 'Data Science'],
    shortDescription: 'Linear regression model for house price prediction with exploratory data analysis and hyperparameter tuning',
    fullDescription: 'Machine learning project that builds and evaluates a linear regression model to predict house prices from structured feature datasets. Includes thorough exploratory data analysis (EDA) to understand feature distributions, correlations, and outliers; feature engineering and selection; model training with hyperparameter tuning for optimal generalization; and comprehensive visualizations of predictions vs. actual values. Developed as part of the SkillCraft Technology Machine Learning internship program (SCT_ML_1).',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&h=675&fit=crop',
    tags: ['Python', 'Linear Regression', 'scikit-learn', 'Pandas', 'NumPy', 'Matplotlib', 'EDA', 'Jupyter Notebook'],
    metrics: { algorithm: 'Linear Regression', technique: 'EDA + Hyperparameter Tuning', type: 'Supervised Regression' },
    github: 'https://github.com/Jaideep193/SCT_ML_1',
    liveDemo: '#',
    featured: false,
  },
  {
    id: 12,
    title: 'Customer Segmentation (K-Means Clustering)',
    category: ['AI/ML', 'Data Science'],
    shortDescription: 'K-Means clustering model for customer segmentation using the Mall Customers dataset with feature engineering',
    fullDescription: 'Machine learning project applying K-Means clustering for customer segmentation on the Mall Customers dataset. Involves feature engineering to extract meaningful attributes (age, annual income, spending score), optimal cluster count determination via the Elbow method, model training, and visualization of distinct customer segments. Provides actionable insights for targeted marketing strategies. Developed as part of the SkillCraft Technology Machine Learning internship program (SCT_ML_2).',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=675&fit=crop',
    tags: ['Python', 'K-Means Clustering', 'scikit-learn', 'Pandas', 'NumPy', 'Matplotlib', 'Feature Engineering', 'Jupyter Notebook'],
    metrics: { algorithm: 'K-Means Clustering', dataset: 'Mall Customers', selection: 'Elbow Method' },
    github: 'https://github.com/Jaideep193/SCT_ML_2',
    liveDemo: '#',
    featured: false,
  },
  {
    id: 13,
    title: 'Big Data Analytics on E-Commerce (Brazilian Olist)',
    category: 'Data Science',
    shortDescription: 'Big data analytics on e-commerce datasets including the Brazilian Olist marketplace with interactive HTML reporting',
    fullDescription: 'End-to-end big data analytics project on the Brazilian Olist marketplace dataset — one of the most comprehensive public e-commerce datasets. Performs large-scale multi-table data processing and integration across orders, products, customers, sellers, payments, and reviews. Conducts exploratory analysis, trend identification, business intelligence extraction, and generates interactive HTML visualizations for stakeholder reporting. Demonstrates practical big data engineering and analytical skills on real-world commercial data.',
    image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1200&h=675&fit=crop',
    tags: ['Python', 'Pandas', 'SQL', 'Big Data', 'Brazilian Olist Dataset', 'Data Analytics', 'HTML Visualization'],
    metrics: { dataset: 'Brazilian Olist', output: 'Interactive HTML', tables: 'Multi-table e-commerce' },
    github: 'https://github.com/Jaideep193/BigData',
    liveDemo: '#',
    featured: false,
  },
]

// Education data
export const educationData = [
  {
    id: 1,
    title: 'Bachelor of Engineering - ISE',
    institution: 'JSS Academy Of Technical Education, Bangalore',
    year: '2022 - 2026',
    details: 'Specialized in AI/ML, Cloud Computing, Full-Stack Development',
    cgpa: '9.03+',
    icon: '🎓',
  },
  {
    id: 2,
    title: 'PUC (XII)',
    institution: 'Rock Valley Residential PU College, Kolar',
    year: '2020 - 2022',
    details: 'Physics, Chemistry, Mathematics, Biology',
    percentage: '96.33%',
    icon: '📚',
  },
  {
    id: 2,
    title: 'SSLC (X)',
    institution: 'Sri Venu Vidya Samasthe, Srinivaspura',
    year: '2019 - 2020',
    details: 'Mathematics, Science, Social Studies, English, Kannada, Hindi',
    percentage: '96%',
    icon: '📚',
  },
]

// Certifications data
export const certificationsData = [
  {
    id: 1,
    title: 'Microsoft Azure Fundamentals (AZ-900)',
    institution: 'Microsoft',
    year: '2025',
    details: 'Cloud concepts, Azure architecture and services, Azure management and governance',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-us/JaideepMC-3064/29E89F813C34FCC4?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  },
  {
    id: 2,
    title: 'Microsoft Azure Data Fundamentals (DP-900)',
    institution: 'Microsoft',
    year: '2025',
    details: 'Core data concepts, Relational data on Azure, Non-relational data on Azure, Analytics workload on Azure',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-us/JaideepMC-3064/A215EF73E5076D0E?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  },
  {
    id: 3,
    title: 'Microsoft Power Platform Fundamentals (PL-900)',
    institution: 'Microsoft',
    year: '2025',
    details: 'Business value of Microsoft Power Platform, Power Platform environment, Capabilities of Power Apps, Power Automate and Power Pages',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-us/JaideepMC-3064/2B8526E6FA0DBCDF?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  },
  {
    id: 4,
    title: 'Oracle Cloud Infrastructure 2025 Certified AI Foundations Associate',
    institution: 'Oracle',
    year: '2024',
    details: 'OCI AI services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=5F30B8171CE9526CCEC5F1F075ECD496D83ED58CE5B53860ACF153E7DC2B2621',
    icon: '🌐',
  },
  {
    id: 5,
    title: 'Oracle Cloud Infrastructure 2025 Certified Foundations Associate',
    institution: 'Oracle',
    year: '2025',
    details: 'OCI services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=D75E5981D26CB89D3BF8529358C9997863620903ABBD91AF58C01CB84BBEE07E',
    icon: '🌐',
  },
  {
    id: 6,
    title: 'NVIDIA-Certified Associate: Generative AI LLMs',
    institution: 'NVIDIA',
    year: '2025',
    details: 'Artificial Intelligence (AI), Large Language Models (LLM), Machine Learning, Deep Learning',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/sco/2/21/Nvidia_logo.svg',
    logoColor: 'text-green-500',
    link: 'https://www.credly.com/badges/2081a2fc-91d3-4edb-9035-3bbf67da7eef/linked_in_profile',
    icon: '⚙️🤖🧠',
  },
  {
    id: 7,
    title: 'Neo4j Certified Professional',
    institution: 'GraphAcademy',
    year: '2025',
    details: 'Neo4j Fundamentals, Cypher Fundamentals, Using Neo4j with Python, Graph Data Modeling Fundamentals, Importing Data Fundamentals, Intermediate Cypher Queries',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/neo4j/neo4j-original.svg',
    logoColor: 'text-cyan-400',
    link: 'https://graphacademy.neo4j.com/c/8ce96653-983f-4c97-8b56-dd8bd6fe1264/',
    icon: '🕸️',
  },
  {
    id: 8,
    title: 'Oracle Cloud Infrastructure 2025 Certified Generative AI Professional',
    institution: 'Oracle',
    year: '2025',
    details: 'OCI AI services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=E6E7536E5B4BC66E997ED7250699B2D7F78842F92A8E5FDF1FD3639CDDE01782',
    icon: '🌐',
  },
  {
    id: 9,
    title: 'Oracle Cloud Infrastructure 2025 Certified Data Science Professional',
    institution: 'Oracle',
    year: '2025',
    details: 'OCI Data and ML services, infrastructure architecture, cloud deployment',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    logoColor: 'text-red-600',
    link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=88552EA17855BFDA1C2E1C0B4F66D9EAECDEF161578F5F97793CF231D280360C',
    icon: '🌐',
  },
  {
    id: 10,
    title: 'Microsoft Azure AI Fundamentals (AI-900)',
    institution: 'Microsoft',
    year: '2026',
    details: 'Cloud concepts, Azure AI Workloads, ML, Gen-AI, Computer Vision, NLP, Responsibilities of AI',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    logoColor: 'text-blue-500',
    link: 'https://learn.microsoft.com/api/credentials/share/en-in/JaideepMC-3064/4B39B5884E329D4F?sharingId=6788F3C5B1756A98',
    icon: '☁️',
  }
]

// Internships data
export const internshipsData = [
  {
    id: 4,
    title: 'Full Stack Development Intern',
    company: 'VrishankSoft (OPC) Pvt Ltd',
    duration: 'February 2026 - May 2026',
    location: 'On-site · Bengaluru',
    details: 'Built SkillForge — an adaptive skill learning platform (W3Schools × Duolingo × GitHub Copilot) — and a multi-role Django E-Commerce application over a structured 90-day internship.',
    achievements: '🎓 SkillForge: OAuth 2.0 + auto PDF certificates + admin analytics | 🛒 3-role E-Commerce app (Admin, Seller, Customer) with Django & MySQL',
    responsibilities: [
      'Architected and delivered SkillForge, a full-stack adaptive learning platform (React 18 + TypeScript, Django 5 REST Framework) with structured skill tracks, XP-based gamification, interactive quizzes, and Monaco Editor in-browser code editor; deployed via Docker Compose + Nginx with GitHub Actions CI/CD',
      'Integrated Judge0 sandboxed code execution engine supporting 40+ programming languages, enabling learners to write, run, and validate code directly in-browser with real-time output and test case feedback',
      'Engineered automated PDF certificate pipeline using ReportLab with embedded QR code verification; triggered on course completion and delivered via Django EmailMultiAlternatives with HTML email templates',
      'Implemented OAuth 2.0 single sign-on (Google & GitHub) using Django REST Framework, SimpleJWT, and django-allauth; built React TypeScript callback handlers and JWT-protected routes across all user roles',
      'Built ShopNest, a production-ready MERN e-commerce platform (MongoDB, Express.js, React, Node.js) with role-based access control, Stripe & Razorpay payment gateway integration, Cloudinary CDN image hosting, multi-step checkout, and bcrypt (12-round) password hashing',
      'Designed multi-database architecture — PostgreSQL as primary store with Django ORM, Redis for session caching and Celery task queuing, MongoDB for activity logs — and built Recharts admin analytics dashboard tracking enrollment, XP, and course completion rates',
    ],
    skills: ['React.js', 'TypeScript', 'Django', 'Node.js', 'Express.js', 'MongoDB', 'PostgreSQL', 'Redis', 'Python', 'Docker', 'OAuth 2.0', 'JWT', 'JavaScript', 'Bootstrap', 'ReportLab'],
    icon: '💻',
  },
  {
    id: 3,
    title: 'AI & Data Analytics Intern',
    company: 'Edunet Foundation | AICTE | Shell (Skills4Future)',
    duration: 'April 2025',
    location: 'Bengaluru, India (Virtual)',
    details: 'Developed an early forest fire detection system using Convolutional Neural Networks (CNNs)',
    achievements: '🔥 95% accuracy | 🚀 Real-time inference | 🌍 Environmental impact solution',
    responsibilities: [
      'Developed CNN-based forest fire detection system achieving 95% classification accuracy on test data',
      'Implemented comprehensive image processing pipeline with resizing, normalization, and advanced data augmentation techniques',
      'Designed and trained deep CNN architecture using TensorFlow with optimized feature extraction layers',
      'Achieved exceptional model performance with high precision, recall, and F1-score for reliable fire detection',
      'Built production-ready solution for environmental monitoring with potential integration into disaster management systems',
    ],
    skills: ['Python', 'TensorFlow', 'CNNs', 'Computer Vision', 'Deep Learning', 'Image Processing', 'Keras'],
    icon: '🔥',
  },
  {
    id: 2,
    title: 'AI/ML Intern',
    company: 'TechSaksham | Microsoft & SAP (CSR Initiative)',
    duration: 'November 2024 - December 2024',
    location: 'Bengaluru, India (Remote)',
    details: 'Developed a real-time Facial Attendance System using Python, OpenCV, and Machine Learning',
    achievements: '✅ 98% face recognition accuracy',
    responsibilities: [
      'Developed real-time Facial Attendance System with automated webcam-based identification and attendance recording',
      'Implemented LBPH (Local Binary Patterns Histogram) face recognition achieving 98% accuracy under varied lighting conditions',
      'Designed end-to-end data pipeline for dataset creation, model training, and persistent storage of weights and mappings',
      'Built automated attendance logging system recording Name, Date, Time with duplicate prevention mechanisms',
      'Created modular architecture suitable for classroom attendance, employee tracking, and access control systems',
    ],
    skills: ['Python', 'OpenCV', 'Machine Learning', 'LBPH', 'Computer Vision', 'Image Processing'],
    icon: '🤖',
  },
  {
    id: 1,
    title: 'Data Analytics Intern',
    company: 'VOIS',
    duration: 'October 2024 - November 2024',
    location: 'Bangalore, India (Remote)',
    details: 'Analyzed business data to identify trends, patterns, and actionable insights',
    achievements: '📈 Improved data query performance by 35% | 📊 Created 8+ interactive dashboards',
    responsibilities: [
      'Analyzed business data to identify trends, patterns, and actionable insights using statistical methods',
      'Created data visualizations and interactive dashboards using Excel, SQL, and Python for stakeholder presentations',
      'Performed rigorous statistical analysis and A/B testing on datasets to validate hypotheses',
      'Optimized complex SQL queries and database operations achieving 35% faster data retrieval',
      'Translated complex data findings into clear, actionable business recommendations for management',
    ],
    skills: ['Python', 'SQL', 'Excel', 'Data Visualization', 'Statistical Analysis', 'Tableau'],
    icon: '📊',
  },
]

// Accomplishments data
export const accomplishmentsData = [
  {
    id: 1,
    title: 'Participated in Tesco Retail Media InnoItion Hackathon',
    achievement: 'Built AI-Powered Ad Design Platform',
    details: 'Organized by Tesco, developed ADGENESIS, an AI-powered design platform that generates ads, posters, and social posts using React, FastAPI, and a custom GPT-2 model',
    date: '2025-2026',
    impact: 'Selected as one of the top 15 teams for final round out of 8700 candidates and 2000+ team entries.',
    icon: '👨‍💻 ',
  },
  
  {
    id: 2,
    title: 'Participated in Quantum Quest 24HR Hackathon',
    achievement: 'Built Arrhythmia Detection System with 98.89% accuracy',
    details: 'Organized by C. Byre Gowda Institute of Technology, developed an Arrhythmia detection system to solve a real-world problem',
    date: '2025',
    impact: 'Out of 65+ teams, our project was selected in the top 10 for its creativity and potential impact',
    icon: ' 👩‍💻',
  },
  {
    id: 3,
    title: 'Participated Hack Together: AI Agents Hackathon',
    achievement: 'Built AI Chatbot',
    details: 'Organized by Microsoft, developed an AI chatbot using Azure OpenAI and Power Platform for a real-world use case',
    date: '2025',
    impact: 'Got $200 free Azure credits and mentorship from Microsoft AI experts throughout the hackathon',
    icon: '📄',
  },
  {
    id: 4,
    title: 'Participated in Google Cloud Arcade Program',
    achievement: 'Learned Google Cloud Skills and Built Projects',
    details: 'Completed 10+ Google Cloud Arcade quests covering core GCP services, AI/ML, and cloud architecture. Built hands-on projects and earned badges for each quest',
    date: '2025',
    impact: 'Reached Legend status in Google Cloud Arcade, demonstrating proficiency in GCP and cloud-native development and earned Google swag for completing quests and received 600 Google Cloud credits',
    icon: '🏆',
  },
  {
    id: 5,
    title: 'Participated in Bhartiya Antariksh Hackathon 2025',
    achievement: 'Built Forest Fire Detection System',
    details: 'Organized by ISRO and Hack2Skill, developed a real-time forest fire detection system using CNNs to address environmental challenges',
    date: '2025',
    impact: 'Innovative approach to environmental monitoring',
    icon: '🚀',
  },
  {
    id: 6,
    title: 'Participated in Paranox 2.O Hackathon',
    achievement: 'Academic Excellence',
    details: 'Participated in Paranox 2.0 Hackathon, organized by TechXNinjas, held from 20th August 2025 to 16th November 2025.',
    date: '2025',
    impact: 'Over 1,552 projects and 20,119 students participated nationwide ',
    icon: '🌟',
  },
  {
    id: 7,
    title: 'Participated in Elite Coders Winter of Code (ECWOC) 2025',
    achievement: 'Academic Excellence',
    details: 'Participated in Elite Coders Winter of Code (ECWOC) 2025, organized by Elite Coders',
    date: '2025',
    impact: '5000+ participants, demonstrating dedication to open source and the developer community',
    icon: '🌟',
  },
  {
    id: 8,
    title: 'Gemini Certified University Student from Google for Education',
    achievement: 'Academic Excellence',
    details: 'Certified in Gemini AI by Google for Education, demonstrating proficiency in using Gemini for AI development and applications',
    date: '2025',
    impact: 'Recognized by Google for Education for AI proficiency, showcasing commitment to learning and applying cutting-edge AI technologies',
    icon: '👩‍💻',
  },
  {
    id: 9,
    title: 'NPTEL Online Certification for Python for Data Science (Elite🏅)!',
    achievement: 'Academic Excellence',
    details: 'Completed the NPTEL Online Certification for Python for Data Science, demonstrating proficiency in Python programming and data science concepts',
    date: '2025',
    impact: 'Scored 80/100 and in top 5 percentile, showcasing strong understanding of Python for data science and commitment to continuous learning',
    icon: '👩‍💻',
  },
  {
    id: 10,
    title: 'Attended the Google Cloud virtual Security Summit (Asia Pacific)',
    achievement: 'Academic Excellence',
    details: 'Received recognition! Attending 5+ knowledge-packed sessions has enriched my knowledge of AI-driven cloud security and current industry trends',
    date: '2025',
    impact: 'Attended 5+ sessions on AI-driven cloud security, gaining insights into the latest trends and best practices in cloud security from Google experts',
    icon: '🌟',
  },
  {
    id: 11,
    title: 'Attended AWS Summit India',
    achievement: 'Academic Excellence',
    details: 'AWS Summit India provided a compelling look into the future of digital infrastructure, reaffirming that the conversation has shifted from mere cloud adoption to cloud-driven business acceleration',
    date: '2025',
    impact: 'Received 25 USD AWS credits and attended sessions on cloud-driven business acceleration, gaining insights into how AWS is enabling innovation and transformation across industries',
    icon: '👩‍💻',
  },
  {
    id: 12,
    title: 'Successfully completed the Machine Learning Specialization by DeepLearning.AI and Stanford Online and Stanford University by instructor Andrew Ng on Coursera',
    achievement: 'Academic Excellence',
    details: 'Completed the Machine Learning Specialization, demonstrating proficiency in machine learning concepts and applications',
    date: '2025',
    impact: 'Gained comprehensive understanding of machine learning algorithms and their practical applications, enhancing my skills in AI and data science',
    icon: '👩‍💻',
  },
  {
    id: 13,
    title: 'Officially completed the IBM Machine Learning Professional Certificate',
    achievement: 'Academic Excellence',
    details: 'Completed the IBM Machine Learning Professional Certificate, demonstrating proficiency in machine learning concepts and applications',
    date: '2025',
    impact: 'Gained comprehensive understanding of machine learning algorithms and their practical applications, enhancing my skills in AI and data science',
    icon: '👩‍💻',
  },
  {
    id: 14,
    title: ' Participate in the IBM TechXchange Dev Day: Open Source LLMs 🌐🤖',
    achievement: 'Academic Excellence',
    details: ' Attended the IBM TechXchange Dev Day focused on Open Source Large Language Models (LLMs), gaining insights into the latest advancements and applications of LLMs in AI development',
    date: '2025',
    impact: 'Gained valuable knowledge on open source LLMs and their impact on AI development, showcasing commitment to staying updated with cutting-edge AI technologies',
    icon: '👩‍💻',
  },
]

// Statistics
export const stats = [
  { label: 'Projects Completed', value: '13+' },
  { label: 'Certifications', value: '4' },
  { label: 'Years Experience', value: '3+' },
  { label: 'Happy Clients', value: '100%' },
]
